### PR TITLE
TextBuffer backup conversion for old VTT source data

### PR DESCRIPTION
**Pull request by paullinnerud**
Desktop VTT uses the Windows MultiByteToWideChar() to perform text conversion from source data to wide characters. It appears that when there is problem with the conversion, MultiByteToWideChar() will will not fail but risk bad data. However for this VTT where we support multiple platforms we use std::codecvt_utf8_utf16 which appears to throw or fail with bad conversion. Some super old source data in a font seemed to work on desktop VTT but failed in this compiler. Added a naive conversion of std::codecvt_utf8_utf16 fails. This should be fine because most even really old source data should be ascii. 

This PR also updates the Visual Studio tools set and addresses a Python change on support of setuptools.

### CODE REVIEW

**Comment by HinTak** [comment]
Hmm, on unix-like system, the iconv* family of function has a conversation mode which ignore errors.

**Comment by HinTak** [comment]
See https://en.m.wikipedia.org/wiki/Iconv .
The command line has this option https://pubs.opengroup.org/onlinepubs/9699919799/utilities/iconv.html but the API doesn't 
https://pubs.opengroup.org/onlinepubs/009695399/functions/iconv.html - nonetheless, you can probably just reference the source code of the command line utility how it is done.

**Comment by paullinnerud** [comment]
I'll take a look, thanks.

**Comment by HinTak** [comment]
There is a spelling mistake with "naive" in the code, btw.

**Comment by HinTak** [comment]
The really old data is probably Latin1 / cp1252, to fail as utf8. (Quite common)

**Pull request merged**
