### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Comment by HinTak** [comment]
I'll personally prefer not to push for this kind of "premature tidying" change though - it could be useful functionality that Microsoft might re-add later, for example, and it interfere with others' work-in-progress: somebody else might actually want to fix warnings etc inside those removed code, even if that section is not used. 

If it bothers somebody, a pair of "#ifdef 0" "#endif" is preferable.

**Comment by simoncozens** [comment]
It’s easier to get your head around the code if there’s less of it.

**Comment by HinTak** [comment]
Well, it could stay in your own fork - that's why I have my opencompiler branch (and contains things that are not yet accepted by upstream, and some materials probably won't be acceptable to upstream, and I don't have to be too careful about not breaking visual studio builds), and have separate cherry-pick to new branches for pulls which contains "no need to debate" changes...

**Review by paullinnerud — APPROVED** [review]
It seems reasonable to remove these, especially area.cpp and area.h. Reducing from VTT to vttcompile was mostly an exercise in removing code used by VTT but not used by vttcompile. The only place I really added code was to parse the glyph structure. VTT uses the rasterizer to parse the glyph data and the rasterizer is not included in vttcompile.

**Comment by HinTak** [comment]
It would be nice if the rasterizer is also released, even if in a binary-only/plug-in external-add-on modular form.

**Comment by paullinnerud** [comment]
We would like to fully open source VTT at some point. The rasterizer as binary-only/plug-in external could be a possibility.

**Pull request merged**
