### PR TITLE
Add Markdown formatted docx documents

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR adds Markdown formatted documentation for the current docx content.  This was a pandoc conversion to GFM with  Markdown / HTML manual edits for consistent code blocks across the docx and md documents.  There were no content edits.

### CODE REVIEW

**Comment by paullinnerud** [comment]
Thanks for converting those documents to markdown. I think that's a better long term solution than docx for this type of project. Some point it would be nice to merge those "update" documents in with the standard documentation and possibly abandon the CHM file for a better solution.

**Comment by HinTak** [comment]
This is the 2nd upstream change that I do not want to include in my opencompiler-port branch.

**Comment by twardoch** [comment]
CHM is just packaged HTML. 

Microsoft uses Markdown extensively these days (even the OpenType spec these days is in Markdown AFAIK). Converting Markdown to HTML is simple, and packaging the result into CHM is easy. 

Markdown is certainly a better format than ancient .doc

**Comment by HinTak** [comment]
I agree about CHM - it is just html; the microsoft html parser is a bit more tolerant than others, so the html can be polished to be more standard-compliant than what the microsoft chm compiler / html parser tolerances.

What I disagree on is that reference and essentially frozen documents be converted away from the format which it would most likely, if ever, updated at all, by the people who are most likely to ever update them, if at all.

These three documents, actually on my private repo, I have them as "frozen" pdf's.

**Pull request merged**
